# Build the WinForms port. No SDK - this compiler ships with Windows.
#
#   .\build.ps1            a dev build: titled "Polyclicker dev", the muted
#                          icon, file version x.y.z.<commits since the tag>
#   .\build.ps1 -Release   the release: x.y.z.0 and the real icon
param([switch]$Release)
$ErrorActionPreference = "Stop"
$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$csc = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
$out = Join-Path $dir "Polyclicker.exe"
$manifest = Join-Path $dir "app.manifest"

# The version is written once, in AssemblyInfo.cs. The file version and the
# dev/release stamp are generated here so a build that isn't the release
# says so - in its title, its icon, and its Properties sheet.
$base = (Select-String -Path (Join-Path $dir "AssemblyInfo.cs") `
    -Pattern 'AssemblyVersion\("(\d+\.\d+\.\d+)\.\d+"\)').Matches[0].Groups[1].Value
if ($Release) {
  $rev = 0; $stamp = "release"; $ico = Join-Path $dir "app.ico"
} else {
  $rev = 0
  try {
    $tag = git -C $dir describe --tags --abbrev=0 2>$null
    if ($tag) { $rev = [int](git -C $dir rev-list --count "$tag..HEAD" 2>$null) }
  } catch { }
  if ($rev -lt 1) { $rev = 1 }          # at the tag with edits still counts as dev
  $stamp = "dev"; $ico = Join-Path $dir "app-dev.ico"
}
$fileVer = "$base.$rev"
@"
// Generated by build.ps1 on every build; not committed.
[assembly: System.Reflection.AssemblyFileVersion("$fileVer")]
[assembly: System.Reflection.AssemblyInformationalVersion("$stamp")]
"@ | Set-Content -Path (Join-Path $dir "BuildInfo.cs") -Encoding utf8

$src = Get-ChildItem -Path $dir -Filter *.cs | ForEach-Object { $_.FullName }
# /win32icon puts it on the exe itself (Explorer, taskbar pin); the embedded
# resource is the same file read back at runtime for the window and the tray
& $csc /nologo /optimize+ /target:winexe /out:$out `
    /win32icon:$ico "/resource:$ico,Polyclicker.app.ico" `
    "/win32manifest:$manifest" `
    /r:System.dll /r:System.Drawing.dll /r:System.Windows.Forms.dll `
    /r:System.IO.Compression.dll /r:System.IO.Compression.FileSystem.dll `
    $src
if ($LASTEXITCODE -eq 0) {
  "built: $out  $fileVer $stamp  ({0:N0} bytes)" -f (Get-Item $out).Length
} else {
  "BUILD FAILED ($LASTEXITCODE)"
}
exit $LASTEXITCODE
